-- Create trigger to update account balance when transactions change
-- DISABLED: This trigger is now properly created in migration 20251214000000
-- Drop old triggers from previous migrations
-- DROP TRIGGER IF EXISTS on_transaction_change_update_account ON public.transactions;
-- DROP TRIGGER IF EXISTS on_transaction_update_goal ON public.transactions;
-- DROP TRIGGER IF EXISTS update_account_balance_trigger ON public.transactions;
-- CREATE TRIGGER update_account_balance_trigger
--   AFTER INSERT OR UPDATE OR DELETE ON public.transactions
--   FOR EACH ROW
--   EXECUTE FUNCTION public.update_account_balance_from_transaction();

-- Create trigger to sync goal with account balance when account changes
-- DISABLED: This trigger is now properly created in migration 20251214000000
-- DROP TRIGGER IF EXISTS sync_goal_balance_trigger ON public.accounts;
-- CREATE TRIGGER sync_goal_balance_trigger
--   AFTER UPDATE OF balance ON public.accounts
--   FOR EACH ROW
--   EXECUTE FUNCTION public.sync_goal_with_account_balance();

-- Create trigger to update goal from transaction when transaction has goal_id
-- DISABLED: This trigger is now properly created in migration 20251214000000
-- DROP TRIGGER IF EXISTS update_goal_from_transaction_trigger ON public.transactions;
-- CREATE TRIGGER update_goal_from_transaction_trigger
--   AFTER INSERT ON public.transactions
--   FOR EACH ROW
--   WHEN (NEW.goal_id IS NOT NULL)
--   EXECUTE FUNCTION public.update_goal_from_transaction();